### ISSUE TITLE
course_section_cm_completion is deprecated

### ISSUE THREAD

**Issue by mudrd8mz** [lmswithai/moodle-theme_simplest#1]
When using the theme in latest 3.11 (which is claimed to be supported), I am getting the following warning:

    course_section_cm_completion is deprecated and is being replaced by the activity_information output component.

    line 441 of /course/renderer.php: call to debugging()
    line 213 of /theme/simplest/classes/output/core/course_renderer.php: call to core_course_renderer->course_section_cm_completion()
    line 836 of /course/renderer.php: call to theme_simplest_core_course_renderer->course_section_cm()
    line 75 of /theme/simplest/classes/output/core/course_renderer.php: call to core_course_renderer->course_section_cm_list_item()
    line 885 of /course/format/renderer.php: call to theme_simplest_core_course_renderer->course_section_cm_list()
    line 57 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
    line 278 of /course/view.php: call to require()

![image](https://user-images.githubusercontent.com/85831/137540555-4c1fadc0-fb5b-4b3f-8ec6-9f390893a155.png)

**Comment by lmswithai** [comment]
Thank you for your submission.
We fixed that in version 1.1.0.
